# TABLA REGISTRA

CREATE TABLE REGISTRA (
	cif VARCHAR(5),
	dni VARCHAR(5),
	codigo VARCHAR(5),
	medio VARCHAR(15) NOT NULL,
	CONSTRAINT PK_REGISTRA PRIMARY KEY(cif, dni, codigo)
);

# TABLA DISTRIBUYE

CREATE TABLE DISTRIBUYE (
	cif VARCHAR(5),
	codigo VARCHAR(5) NOT NULL,
	cantidad int NOT NULL,
	CONSTRAINT PK_DISTRIBUYE PRIMARY KEY(cif, codigo)
);

# TABLA DESARROLLA

CREATE TABLE DESARROLLA (
	id_fab VARCHAR(5),
	codigo VARCHAR(5) NOT NULL,
	CONSTRAINT PK_DESARROLLA PRIMARY KEY(id_fab, codigo)
);

# TABLA CLIENTE

CREATE TABLE CLIENTE (
	dni VARCHAR(5),
	nombre VARCHAR(20) NOT NULL,
	edad int NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(dni)
);

# TABLA COMERCIO

CREATE TABLE COMERCIO (
	cif VARCHAR(5),
	nombre VARCHAR(20) NOT NULL,
	ciudad VARCHAR(15) NOT NULL,
	CONSTRAINT PK_COMERCIO PRIMARY KEY(cif)
);

# TABLA PROGRAMA

CREATE TABLE PROGRAMA (
	codigo VARCHAR(5),
	nombre VARCHAR(30) NOT NULL,
	version VARCHAR(20),
	CONSTRAINT PK_PROGRAMA PRIMARY KEY(codigo)
);

# TABLA FABRICANTE

CREATE TABLE FABRICANTE (
	id_fab VARCHAR(5),
	nombre VARCHAR(20) NOT NULL,
	pais VARCHAR(15) NOT NULL,
	CONSTRAINT pk_FABRICANTE PRIMARY KEY(id_fab)
);

# CREACIÓN DE CLAVES AJENAS

ALTER TABLE DESARROLLA
	ADD CONSTRAINT fk_DESARROLLA_FABRICANTE
	FOREIGN KEY (id_fab)
	REFERENCES FABRICANTE(id_fab);
    

ALTER TABLE DESARROLLA
	ADD CONSTRAINT fk_DESARROLLA_PROGRAMA
	FOREIGN KEY (codigo)
	REFERENCES PROGRAMA(codigo);


ALTER TABLE DISTRIBUYE
	ADD CONSTRAINT fk_DISTRIBUYE_COMERCIO
	FOREIGN KEY (cif)
	REFERENCES COMERCIO(cif);


ALTER TABLE DISTRIBUYE
	ADD CONSTRAINT fk_DISTRIBUYE_PROGRAMA
	FOREIGN KEY (codigo)
	REFERENCES PROGRAMA(codigo);


ALTER TABLE REGISTRA
	ADD CONSTRAINT fk_REGISTRA_COMERCIO
	FOREIGN KEY (cif)
	REFERENCES COMERCIO(cif);


ALTER TABLE REGISTRA
	ADD CONSTRAINT fk_REGISTRA_CLIENTE
	FOREIGN KEY (dni)
	REFERENCES CLIENTE(dni);


ALTER TABLE REGISTRA
	ADD CONSTRAINT fk_REGISTRA_PROGRAMA
	FOREIGN KEY (codigo)
	REFERENCES PROGRAMA(codigo);


	
